name: Run ROC Sensor in GitHub Actions

on:
  workflow_dispatch:

jobs:
  run-roc:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare config file
        run: |
          mkdir -p ./roc-config ./roc-output
          cat <<'EOF' > ./roc-config/pattern.yaml
          patterns:
            - id: "api_key"
              regex: "(?i)api[_-]?key\\s*[:=]\\s*[A-Za-z0-9\\-_]{16,}"
            - id: "authorization_bearer"
              regex: "Bearer\\s+[A-Za-z0-9\\-._~+/]+=*"
            - id: "email"
              regex: "[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}"
          EOF
          ls -l ./roc-config/
      - name: Run ROC container (privileged)
        run: |
          docker run -d --name roc-test \
            --privileged \
            --pid=host \
            --network=host \
            -v /proc:/proc \
            -v /sys:/sys \
            -v /usr/lib/x86_64-linux-gnu/libssl.so.3:/usr/lib64/libssl.so.3 \
            -v /usr/lib/x86_64-linux-gnu/libcrypto.so.3:/usr/lib64/libcrypto.so.3 \
            -v ${{ github.workspace }}/roc-output:/tmp/roc-output \
            -v ${{ github.workspace }}/roc-config:/tmp/roc-config:ro \
            hanshal785/roc:vm \
            --server-url https://api.codexsecurity.io \
            --api-key dummyapikey1234567890 \
            --patterns /tmp/roc-config/pattern.yaml \
            --watch /tmp/roc-output
      - name: Simulate curl traffic
        run: |
          echo "Generating curl traffic..."
          curl -s https://example.com > /dev/null || true
          curl -s -X POST https://httpbin.org/post -d '{"roc":"test"}' \
            -H "Content-Type: application/json" > /dev/null || true
      - name: Print ROC logs
        run: |
          echo "Sleep 70"
          sleep 70
          echo "Fetching ROC container logs..."
          docker logs roc-test || true
      - name: Cleanup
        if: always()
        run: |
          docker rm -f roc-test || true
          rm -rf /tmp/roc-output /tmp/roc-config
