name: Run ROC Sensor in GitHub Actions

on:
  workflow_dispatch:

jobs:
  run-roc:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare config file
        run: |
          mkdir -p ./roc-config ./roc-output
          cat <<'EOF' > ./roc-config/pattern.yaml
          patterns:
            - id: "simple_number"
              regex: "1234"
          EOF
          ls -l ./roc-config/

      - name: Run ROC container (privileged)
        run: |
          docker run -d --name roc-test \
            --privileged \
            --pid=host \
            --network=host \
            -v /proc:/proc \
            -v /sys:/sys \
            -v /lib/x86_64-linux-gnu/libssl.so.3:/usr/lib64/libssl.so.3 \
            -v /lib/x86_64-linux-gnu/libcrypto.so.3:/usr/lib64/libcrypto.so.3 \
            -v ${{ github.workspace }}/roc-output:/tmp/roc-output \
            -v ${{ github.workspace }}/roc-config:/tmp/roc-config:ro \
            hanshal785/roc:v3 \
            --server-url https://api.codexsecurity.io \
            --api-key dummyapikey1234567890 \
            --patterns /tmp/roc-config/pattern.yaml \
            --watch /tmp/roc-output
           
          sleep 15

      - name: Simulate curl traffic
        run: |
          echo "Sending test curl ..."
          curl -s -X POST "https://httpbin.org/post" \
            -H "Content-Type: application/json" \
            -d '{"data":"12345667788764"}' > /dev/null || true

      - name: Wait and print logs
        run: |
          sleep 40
          echo "Fetching ROC logs..."
          docker logs roc-test || true
          docker exec roc-test sh -c 'ls /tmp/roc-output'
          docker exec roc-test sh -c 'cat /tmp/roc-output/secrets_*.json || true'

      - name: Cleanup
        if: always()
        run: |
          docker rm -f roc-test || true
          rm -rf ./roc-output ./roc-config
