name: Run ROC Sensor in GitHub Actions

on:
  workflow_dispatch:

jobs:
  run-roc:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare config file
        run: |
          mkdir -p ./roc-config ./roc-output
          cat <<'EOF' > ./roc-config/pattern.yaml
          patterns:
            - id: "api_key"
              regex: "(?i)api[_-]?key\\s*[:=]\\s*[A-Za-z0-9\\-_]{16,}"
            - id: "authorization_bearer"
              regex: "Bearer\\s+[A-Za-z0-9\\-._~+/]+=*"
            - id: "email"
              regex: "[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}"
          EOF
          ls -l ./roc-config/

      - name: Run ROC container (privileged)
        run: |
          docker run -d --name roc-test \
            --privileged \
            --pid=host \
            --network=host \
            -v /proc:/proc \
            -v /sys:/sys \
            -v /lib/x86_64-linux-gnu/libssl.so.3:/usr/lib64/libssl.so.3 \
            -v /lib/x86_64-linux-gnu/libcrypto.so.3:/usr/lib64/libcrypto.so.3 \
            -v ${{ github.workspace }}/roc-output:/tmp/roc-output \
            -v ${{ github.workspace }}/roc-config:/tmp/roc-config:ro \
            hanshal785/roc:v3 \
            --server-url https://api.codexsecurity.io \
            --api-key dummyapikey1234567890 \
            --patterns /tmp/roc-config/pattern.yaml \
            --watch /tmp/roc-output

          sleep 20

      - name: Simulate curl traffic (API key and Bearer)
        run: |
          echo "Generating curl traffic..."
          curl -s https://example.com > /dev/null || true
          
          curl -s -X POST "https://httpbin.org/post?api_key=APIKEY_TEST_ABCDEF123456" \
            -H "Authorization: Bearer TEST_BEARER_TOKEN_123456" \
            -H "Content-Type: application/json" \
            -d '{"api_key":"APIKEY_JSON_1234567890","msg":"trigger"}' \
            > /dev/null || true

      - name: Print ROC logs
        run: |
          echo "Sleeping 70 to allow logs to generate..."
          sleep 70
          echo "Fetching ROC container logs..."
          docker logs roc-test || true
          sleep 5
          docker exec roc-test sh -c 'cat /tmp/roc-output/secrets_*.json || true'

      - name: More simulated curl traffic with API Key
        run: |
          curl -X POST "https://example.com?api_key=DUMMY_KEY_1234567890" \
            -H "Content-Type: application/json" \
            -d '{"api_key":"IN_BODY_KEY_9999999999"}' > /dev/null || true

          sleep 20
          docker logs roc-test || true

      - name: Inside the container - install curl + trigger traffic
        run: |
          docker exec roc-test sh -c 'apt update && apt install -y curl'
          docker exec roc-test sh -c "curl -X POST https://example.com -H 'Content-Type: application/json' -d '{\"api_key\":\"CONTAINER_KEY_ABCDEFG12345\"}'"
          docker logs roc-test || true

      - name: Cleanup
        if: always()
        run: |
          docker rm -f roc-test || true
          rm -rf /tmp/roc-output /tmp/roc-config
